### ISSUE TITLE
Base Pytorch Version or tag

### ISSUE THREAD

**Issue by fengyuanyu1** [thustorage/Medusa#3]
Hello, @ShaoxunZeng , can u provide the base tag for original Pytorch/vllm/xformers?

**Comment by ShaoxunZeng** [comment]
We will release our paper after it is camera-ready.

**Comment by ShaoxunZeng** [comment]
PyTorch: 6c8c5ad5eaf47a62fafbb4a2747198cbffbf1ff0
vllm: 5f08050d8d0bfcdaced0fe706cdfc9e311e0f263
xformers: 042abc8aa47d1f5bcc2e82df041811de218924ba

**Comment by fengyuanyu1** [comment]
Thx for your info, @ShaoxunZeng.
Could I know the date for camera-ready submission, I can't wait to read your interesting Medusa.

**Comment by ShaoxunZeng** [comment]
Thanks for your attention, after the camera-ready and the patent application, we will release it as soon as possible.
